name: Build
on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened]
jobs:
    sonarcloud:
        name: SonarCloud
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
            - name: Install dependencies
              run: npm i
            - name: Set up environment variables
              run: |
                  echo "DB_NAME=${{ secrets.TEST_DB_NAME }}" >> $GITHUB_ENV
                  echo "DB_USER=${{ secrets.TEST_DB_USER }}" >> $GITHUB_ENV
                  echo "DB_PASS=${{ secrets.TEST_DB_PASS }}" >> $GITHUB_ENV
                  echo "DB_PORT=${{ secrets.TEST_DB_PORT }}" >> $GITHUB_ENV
                  echo "DB_HOST=${{ secrets.TEST_DB_HOST }}" >> $GITHUB_ENV
                  echo "SS_SECRET=${{ secrets.TEST_SS_SECRET }}" >> $GITHUB_ENV
                  echo "SS_NAME=${{ secrets.TEST_SS_NAME }}" >> $GITHUB_ENV
                  echo "JWT_SECRET=${{ secrets.TEST_JWT_SECRET }}" >> $GITHUB_ENV
                  echo "JWT_ISSUER=${{ secrets.TEST_JWT_ISSUER }}" >> $GITHUB_ENV
                  echo "JWT_AUDIENCE=${{ secrets.TEST_JWT_AUDIENCE }}" >> $GITHUB_ENV
                  echo "REDIS_HOST=${{ secrets.TEST_REDIS_HOST }}" >> $GITHUB_ENV
                  echo "REDIS_PORT=${{ secrets.TEST_REDIS_PORT }}" >> $GITHUB_ENV
                  echo "APP_NAME=${{ secrets.TEST_APP_NAME }}" >> $GITHUB_ENV
                  echo "PORT=${{ secrets.TEST_PORT }}" >> $GITHUB_ENV
            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
