module.exports = {
    EN: {
        group: 'Default',
        income: ['Work', 'Addition'],
        accounts: ['Cash', 'Bank'],
        categories: [
            'Food',
            'Housing',
            'Transport',
            'Health and Medicine',
            'Education',
            'Entertainment',
            'Leisure and Travel',
            'Clothing and Accessories',
            'Communication and Internet',
            'Gifts and Charity',
            'Personal Expenses',
            'Savings and Investments',
        ],
    },
    UA: {
        group: 'За замовчуванням',
        income: ['Робота', 'Додаткові доходи'],
        accounts: ['Готівка', 'Банк'],
        categories: [
            'Харчування',
            'Житло',
            'Транспорт',
            "Здоров'я і медицина",
            'Освіта',
            'Розваги',
            'Відпочинок і подорожі',
            'Одяг і аксесуари',
            "Зв'язок і інтернет",
            'Подарунки та благодійність',
            'Особисті витрати',
            'Заощадження та інвестиції',
        ],
    },
};
