const currency_initial = {
    'da-DK': { currencyCode: 'DKK', currencyName: 'Danish Krone', symbol: 'kr' },
    'el-GR': { currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
    'de-DE': { currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
    'en-US': { currencyCode: 'USD', currencyName: 'US Dollar', symbol: '$' },
    'es-ES': { currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
    'et-ET': { currencyCode: 'ETB', currencyName: 'Ethiopian Birr', symbol: 'Br' },
    'fi-FI': { currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
    'fr-FR': { currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
    'it-IT': { currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
    'nl-NL': { currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
    'no-NO': { currencyCode: 'NOK', currencyName: 'Norwegian Krone', symbol: 'kr' },
    'pt-PT': { currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
    'sv-SE': { currencyCode: 'SEK', currencyName: 'Swedish Krona', symbol: 'kr' },
    'uk-UA': { currencyCode: 'UAH', currencyName: 'Ukrainian Hryvnia', symbol: '₴' },
    'ru-RU': { currencyCode: 'RUB', currencyName: 'Russian Ruble', symbol: '₽' },
    'bg-BG': { currencyCode: 'BGN', currencyName: 'Bulgarian Lev', symbol: 'лв' },
    'cs-CZ': { currencyCode: 'CZK', currencyName: 'Czech Koruna', symbol: 'Kč' },
    'hr-HR': { currencyCode: 'HRK', currencyName: 'Croatian Kuna', symbol: 'kn' },
    'hu-HU': { currencyCode: 'HUF', currencyName: 'Hungarian Forint', symbol: 'Ft' },
    'ja-JP': { currencyCode: 'JPY', currencyName: 'Japanese Yen', symbol: '¥' },
    'ka-GE': { currencyCode: 'GEL', currencyName: 'Georgian Lari', symbol: '₾' },
    'pl-PL': { currencyCode: 'PLN', currencyName: 'Polish Złoty', symbol: 'zł' },
    'pt-BR': { currencyCode: 'BRL', currencyName: 'Brazilian Real', symbol: 'R$' },
    'ro-RO': { currencyCode: 'RON', currencyName: 'Romanian Leu', symbol: 'lei' },
    'sk-SK': { currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
    'sl-SI': { currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
    'tr-TR': { currencyCode: 'TRY', currencyName: 'Turkish Lira', symbol: '₺' },
    'lv-LV': { currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
};

export default currency_initial;
