export const user_initial = {
    'da-DK': {
        group: 'Standard',
        income: ['Arbejde', 'Tillæg'],
        accounts: ['Kontant', 'Bank'],
        categories: [
            'Mad',
            'Bolig',
            'Transport',
            'Sundhed og medicin',
            'Uddannelse',
            'Underholdning',
            'Fritid og rejser',
            'Tøj og tilbehør',
            'Kommunikation og internet',
            'Gaver og velgørenhed',
            'Personlige udgifter',
            'Opsparing og investeringer',
        ],
    },
    'el-GR': {
        group: 'Προεπιλογή',
        income: ['Εργασία', 'Πρόσθετο'],
        accounts: ['Μετρητά', 'Τράπεζα'],
        categories: [
            'Τρόφιμα',
            'Στέγαση',
            'Μεταφορά',
            'Υγεία και ιατρική',
            'Εκπαίδευση',
            'Ψυχαγωγία',
            'Αναψυχή και ταξίδια',
            'Ρούχα και αξεσουάρ',
            'Επικοινωνία και διαδίκτυο',
            'Δώρα και φιλανθρωπία',
            'Προσωπικές δαπάνες',
            'Αποταμίευση και επενδύσεις',
        ],
    },
    'de-DE': {
        group: 'Standard',
        income: ['Arbeit', 'Zusatz'],
        accounts: ['Bargeld', 'Bank'],
        categories: [
            'Lebensmittel',
            'Wohnen',
            'Transport',
            'Gesundheit und Medizin',
            'Bildung',
            'Unterhaltung',
            'Freizeit und Reisen',
            'Kleidung und Accessoires',
            'Kommunikation und Internet',
            'Geschenke und Wohltätigkeit',
            'Persönliche Ausgaben',
            'Sparen und Investitionen',
        ],
    },
    'en-US': {
        group: 'Default',
        income: ['Work', 'Addition'],
        accounts: ['Cash', 'Bank'],
        categories: [
            'Food',
            'Housing',
            'Transport',
            'Health and Medicine',
            'Education',
            'Entertainment',
            'Leisure and Travel',
            'Clothing and Accessories',
            'Communication and Internet',
            'Gifts and Charity',
            'Personal Expenses',
            'Savings and Investments',
        ],
    },
    'es-ES': {
        group: 'Predeterminado',
        income: ['Trabajo', 'Adicional'],
        accounts: ['Efectivo', 'Banco'],
        categories: [
            'Alimentos',
            'Vivienda',
            'Transporte',
            'Salud y medicina',
            'Educación',
            'Entretenimiento',
            'Ocio y viajes',
            'Ropa y accesorios',
            'Comunicación e internet',
            'Regalos y caridad',
            'Gastos personales',
            'Ahorros e inversiones',
        ],
    },
    'et-ET': {
        group: 'Vaikimisi',
        income: ['Töö', 'Lisatulu'],
        accounts: ['Sularaha', 'Pank'],
        categories: [
            'Toit',
            'Eluase',
            'Transport',
            'Tervis ja meditsiin',
            'Haridus',
            'Meelelahutus',
            'Puhkus ja reisimine',
            'Riided ja aksessuaarid',
            'Kommunikatsioon ja internet',
            'Kingitused ja heategevus',
            'Isiklikud kulud',
            'Säästud ja investeeringud',
        ],
    },
    'fi-FI': {
        group: 'Oletus',
        income: ['Työ', 'Lisätulot'],
        accounts: ['Käteinen', 'Pankki'],
        categories: [
            'Ruoka',
            'Asuminen',
            'Liikenne',
            'Terveys ja lääketiede',
            'Koulutus',
            'Viihde',
            'Vapaa-aika ja matkailu',
            'Vaatteet ja tarvikkeet',
            'Viestintä ja internet',
            'Lahjat ja hyväntekeväisyys',
            'Henkilökohtaiset menot',
            'Säästöt ja sijoitukset',
        ],
    },
    'fr-FR': {
        group: 'Défaut',
        income: ['Travail', 'Supplément'],
        accounts: ['Espèces', 'Banque'],
        categories: [
            'Alimentation',
            'Logement',
            'Transport',
            'Santé et médecine',
            'Éducation',
            'Divertissement',
            'Loisirs et voyages',
            'Vêtements et accessoires',
            'Communication et internet',
            'Cadeaux et charité',
            'Dépenses personnelles',
            'Épargne et investissements',
        ],
    },
    'it-IT': {
        group: 'Predefinito',
        income: ['Lavoro', 'Aggiuntivo'],
        accounts: ['Contante', 'Banca'],
        categories: [
            'Cibo',
            'Abitazione',
            'Trasporto',
            'Salute e medicina',
            'Educazione',
            'Intrattenimento',
            'Tempo libero e viaggi',
            'Abbigliamento e accessori',
            'Comunicazione e internet',
            'Regali e beneficenza',
            'Spese personali',
            'Risparmi e investimenti',
        ],
    },
    'nl-NL': {
        group: 'Standaard',
        income: ['Werk', 'Extra'],
        accounts: ['Contant', 'Bank'],
        categories: [
            'Voedsel',
            'Huisvesting',
            'Vervoer',
            'Gezondheid en geneeskunde',
            'Onderwijs',
            'Amusement',
            'Vrije tijd en reizen',
            'Kleding en accessoires',
            'Communicatie en internet',
            'Giften en liefdadigheid',
            'Persoonlijke uitgaven',
            'Sparen en beleggen',
        ],
    },
    'no-NO': {
        group: 'Standard',
        income: ['Arbeid', 'Tillegg'],
        accounts: ['Kontanter', 'Bank'],
        categories: [
            'Mat',
            'Bolig',
            'Transport',
            'Helse og medisin',
            'Utdanning',
            'Underholdning',
            'Fritid og reiser',
            'Klær og tilbehør',
            'Kommunikasjon og internett',
            'Gaver og veldedighet',
            'Personlige utgifter',
            'Sparing og investeringer',
        ],
    },
    'pt-PT': {
        group: 'Padrão',
        income: ['Trabalho', 'Adicional'],
        accounts: ['Dinheiro', 'Banco'],
        categories: [
            'Alimentação',
            'Habitação',
            'Transporte',
            'Saúde e Medicina',
            'Educação',
            'Entretenimento',
            'Lazer e Viagens',
            'Roupa e Acessórios',
            'Comunicação e Internet',
            'Presentes e Caridade',
            'Despesas Pessoais',
            'Poupança e Investimentos',
        ],
    },
    'sv-SE': {
        group: 'Standard',
        income: ['Arbete', 'Tillägg'],
        accounts: ['Kontanter', 'Bank'],
        categories: [
            'Mat',
            'Boende',
            'Transport',
            'Hälsa och medicin',
            'Utbildning',
            'Underhållning',
            'Fritid och resor',
            'Kläder och tillbehör',
            'Kommunikation och internet',
            'Gåvor och välgörenhet',
            'Personliga utgifter',
            'Sparande och investeringar',
        ],
    },

    'uk-UA': {
        group: 'За замовчуванням',
        income: ['Робота', 'Додаткові доходи'],
        accounts: ['Готівка', 'Банк'],
        categories: [
            'Харчування',
            'Житло',
            'Транспорт',
            "Здоров'я і медицина",
            'Освіта',
            'Розваги',
            'Відпочинок і подорожі',
            'Одяг і аксесуари',
            "Зв'язок і інтернет",
            'Подарунки та благодійність',
            'Особисті витрати',
            'Заощадження та інвестиції',
        ],
    },
    'ru-RU': {
        group: 'Стандарт',
        income: ['Работа', 'Дополнение'],
        accounts: ['Наличные', 'Банк'],
        categories: [
            'Еда',
            'Жилье',
            'Транспорт',
            'Здоровье и медицина',
            'Образование',
            'Развлечения',
            'Отдых и путешествия',
            'Одежда и аксессуары',
            'Связь и интернет',
            'Подарки и благотворительность',
            'Личные расходы',
            'Сбережения и инвестиции',
        ],
    },
    'bg-BG': {
        group: 'Стандарт',
        income: ['Работа', 'Допълнително'],
        accounts: ['Кеш', 'Банка'],
        categories: [
            'Храна',
            'Жилище',
            'Транспорт',
            'Здраве и медицина',
            'Образование',
            'Развлечения',
            'Свободно време и пътувания',
            'Дрехи и аксесоари',
            'Комуникации и интернет',
            'Подаръци и благотворителност',
            'Лични разходи',
            'Спестявания и инвестиции',
        ],
    },
    'cs-CZ': {
        group: 'Standardní',
        income: ['Práce', 'Přídavek'],
        accounts: ['Hotovost', 'Banka'],
        categories: [
            'Jídlo',
            'Bydlení',
            'Doprava',
            'Zdraví a medicína',
            'Vzdělání',
            'Zábava',
            'Volný čas a cestování',
            'Oblečení a doplňky',
            'Komunikace a internet',
            'Dárky a charita',
            'Osobní výdaje',
            'Spoření a investice',
        ],
    },
    'hr-HR': {
        group: 'Standard',
        income: ['Posao', 'Dodatno'],
        accounts: ['Gotovina', 'Banka'],
        categories: [
            'Hrana',
            'Stanovanje',
            'Prijevoz',
            'Zdravlje i medicina',
            'Obrazovanje',
            'Zabava',
            'Odmor i putovanja',
            'Odjeća i dodaci',
            'Komunikacija i internet',
            'Pokloni i dobrotvornost',
            'Osobni troškovi',
            'Štednja i investicije',
        ],
    },
    'hu-HU': {
        group: 'Alapértelmezett',
        income: ['Munka', 'Kiegészítő'],
        accounts: ['Készpénz', 'Bank'],
        categories: [
            'Élelmiszer',
            'Lakhatás',
            'Közlekedés',
            'Egészség és gyógyszertár',
            'Oktatás',
            'Szórakozás',
            'Szabadidő és utazás',
            'Ruházat és kiegészítők',
            'Kommunikáció és internet',
            'Ajándékok és jótékonyság',
            'Személyes kiadások',
            'Megtakarítások és befektetések',
        ],
    },
    'ja-JP': {
        group: 'デフォルト',
        income: ['仕事', '追加'],
        accounts: ['現金', '銀行'],
        categories: [
            '食品',
            '住宅',
            '交通',
            '健康と医療',
            '教育',
            'エンターテイメント',
            'レジャーと旅行',
            '衣服とアクセサリー',
            '通信とインターネット',
            '贈り物とチャリティ',
            '個人の支出',
            '貯蓄と投資',
        ],
    },
    'ka-GE': {
        group: 'სტანდარტული',
        income: ['სამუშაო', 'დამატებითი'],
        accounts: ['ნაღდი ფული', 'ბანკი'],
        categories: [
            'საკვები',
            'სახლი',
            'ტრანსპორტი',
            'ჯანმრთელობა და მედიცინა',
            'განათლება',
            'გართობა',
            'დასვენება და მოგზაურობა',
            'ტანსაცმელი და აქსესუარები',
            'კომუნიკაცია და ინტერნეტი',
            'საჩუქრები და სარგებელი',
            'პირადი ხარჯები',
            'დაგროვება და ინვესტიციები',
        ],
    },
    'pl-PL': {
        group: 'Domyślny',
        income: ['Praca', 'Dodatkowe'],
        accounts: ['Gotówka', 'Bank'],
        categories: [
            'Żywność',
            'Mieszkanie',
            'Transport',
            'Zdrowie i medycyna',
            'Edukacja',
            'Rozrywka',
            'Wypoczynek i podróże',
            'Odzież i akcesoria',
            'Komunikacja i internet',
            'Prezenty i dobroczynność',
            'Wydatki osobiste',
            'Oszczędności i inwestycje',
        ],
    },
    'pt-BR': {
        group: 'Padrão',
        income: ['Trabalho', 'Adicional'],
        accounts: ['Dinheiro', 'Banco'],
        categories: [
            'Alimentação',
            'Moradia',
            'Transporte',
            'Saúde e Medicina',
            'Educação',
            'Entretenimento',
            'Lazer e Viagens',
            'Roupas e Acessórios',
            'Comunicação e Internet',
            'Presentes e Caridade',
            'Despesas Pessoais',
            'Poupanças e Investimentos',
        ],
    },
    'ro-RO': {
        group: 'Standard',
        income: ['Muncă', 'Suplimentar'],
        accounts: ['Numerar', 'Bancă'],
        categories: [
            'Alimentație',
            'Locuință',
            'Transport',
            'Sănătate și medicină',
            'Educație',
            'Divertisment',
            'Timp liber și călătorii',
            'Îmbrăcăminte și accesorii',
            'Comunicații și internet',
            'Cadouri și caritate',
            'Cheltuieli personale',
            'Economii și investiții',
        ],
    },
    'sk-SK': {
        group: 'Štandard',
        income: ['Práca', 'Doplnkové'],
        accounts: ['Hotovosť', 'Banka'],
        categories: [
            'Potraviny',
            'Bývanie',
            'Doprava',
            'Zdravie a medicína',
            'Vzdelávanie',
            'Zábava',
            'Voľný čas a cestovanie',
            'Oblečenie a doplnky',
            'Komunikácia a internet',
            'Darčeky a charita',
            'Osobné výdavky',
            'Úspory a investície',
        ],
    },
    'sl-SI': {
        group: 'Standard',
        income: ['Delo', 'Dodatno'],
        accounts: ['Gotovina', 'Banka'],
        categories: [
            'Hrana',
            'Bivanje',
            'Prevoz',
            'Zdravje in medicina',
            'Izobraževanje',
            'Zabava',
            'Prosti čas in potovanja',
            'Oblačila in dodatki',
            'Komunikacija in internet',
            'Darila in dobrodelnost',
            'Osebni izdatki',
            'Varčevanja in naložbe',
        ],
    },
    'tr-TR': {
        group: 'Varsayılan',
        income: ['İş', 'Ek'],
        accounts: ['Nakit', 'Banka'],
        categories: [
            'Gıda',
            'Konut',
            'Ulaşım',
            'Sağlık ve Tıp',
            'Eğitim',
            'Eğlence',
            'Boş Zaman ve Seyahat',
            'Giyim ve Aksesuarlar',
            'İletişim ve İnternet',
            'Hediyeler ve Hayırseverlik',
            'Kişisel Harcamalar',
            'Tasarruf ve Yatırımlar',
        ],
    },
    'lv-LV': {
        group: 'Standarta',
        income: ['Darbs', 'Papildus'],
        accounts: ['Skaidra nauda', 'Banka'],
        categories: [
            'Pārtika',
            'Mājoklis',
            'Transports',
            'Veselība un medicīna',
            'Izglītība',
            'Izklaide',
            'Atpūta un ceļošana',
            'Apģērbi un aksesuāri',
            'Saziņa un internets',
            'Dāvanas un labdarība',
            'Personīgie izdevumi',
            'Ietaupījumi un ieguldījumi',
        ],
    },
};
