export const user_initial = {
    'da-DK': {
        group: 'Standard',
        income: ['Arbejde'],
        accounts: ['Kontant'],
        categories: [
            'Mad',
            'Bolig',
            'Transport',
            'Sundhed og medicin',
            'Uddannelse',
            'Underholdning',
            'Fritid og rejser',
            'Tøj og tilbehør',
            'Gaver og velgørenhed',
        ],
    },
    'el-GR': {
        group: 'Προεπιλογή',
        income: ['Εργασία'],
        accounts: ['Μετρητά'],
        categories: [
            'Τρόφιμα',
            'Στέγαση',
            'Μεταφορά',
            'Υγεία και ιατρική',
            'Εκπαίδευση',
            'Ψυχαγωγία',
            'Αναψυχή και ταξίδια',
            'Ρούχα και αξεσουάρ',
            'Δώρα και φιλανθρωπία',
        ],
    },
    'de-DE': {
        group: 'Standard',
        income: ['Arbeit'],
        accounts: ['Bargeld'],
        categories: [
            'Lebensmittel',
            'Wohnen',
            'Transport',
            'Gesundheit und Medizin',
            'Bildung',
            'Unterhaltung',
            'Freizeit und Reisen',
            'Kleidung und Accessoires',
            'Geschenke und Wohltätigkeit',
        ],
    },
    'en-US': {
        group: 'Default',
        income: ['Work'],
        accounts: ['Cash'],
        categories: [
            'Food',
            'Housing',
            'Transport',
            'Health and Medicine',
            'Education',
            'Entertainment',
            'Leisure and Travel',
            'Clothing and Accessories',
            'Gifts and Charity',
        ],
    },
    'es-ES': {
        group: 'Predeterminado',
        income: ['Trabajo'],
        accounts: ['Efectivo'],
        categories: [
            'Alimentos',
            'Vivienda',
            'Transporte',
            'Salud y medicina',
            'Educación',
            'Entretenimiento',
            'Ocio y viajes',
            'Ropa y accesorios',
            'Regalos y caridad',
        ],
    },
    'et-ET': {
        group: 'Vaikimisi',
        income: ['Töö'],
        accounts: ['Sularaha'],
        categories: [
            'Toit',
            'Eluase',
            'Transport',
            'Tervis ja meditsiin',
            'Haridus',
            'Meelelahutus',
            'Puhkus ja reisimine',
            'Riided ja aksessuaarid',
            'Kingitused ja heategevus',
        ],
    },
    'fi-FI': {
        group: 'Oletus',
        income: ['Työ'],
        accounts: ['Käteinen'],
        categories: [
            'Ruoka',
            'Asuminen',
            'Liikenne',
            'Terveys ja lääketiede',
            'Koulutus',
            'Viihde',
            'Vapaa-aika ja matkailu',
            'Vaatteet ja tarvikkeet',
            'Lahjat ja hyväntekeväisyys',
        ],
    },
    'fr-FR': {
        group: 'Défaut',
        income: ['Travail'],
        accounts: ['Espèces'],
        categories: [
            'Alimentation',
            'Logement',
            'Transport',
            'Santé et médecine',
            'Éducation',
            'Divertissement',
            'Loisirs et voyages',
            'Vêtements et accessoires',
            'Cadeaux et charité',
        ],
    },
    'it-IT': {
        group: 'Predefinito',
        income: ['Lavoro'],
        accounts: ['Contante'],
        categories: [
            'Cibo',
            'Abitazione',
            'Trasporto',
            'Salute e medicina',
            'Educazione',
            'Intrattenimento',
            'Tempo libero e viaggi',
            'Abbigliamento e accessori',
            'Regali e beneficenza',
        ],
    },
    'nl-NL': {
        group: 'Standaard',
        income: ['Werk'],
        accounts: ['Contant'],
        categories: [
            'Voedsel',
            'Huisvesting',
            'Vervoer',
            'Gezondheid en geneeskunde',
            'Onderwijs',
            'Amusement',
            'Vrije tijd en reizen',
            'Kleding en accessoires',
            'Giften en liefdadigheid',
        ],
    },
    'no-NO': {
        group: 'Standard',
        income: ['Arbeid'],
        accounts: ['Kontanter'],
        categories: [
            'Mat',
            'Bolig',
            'Transport',
            'Helse og medisin',
            'Utdanning',
            'Underholdning',
            'Fritid og reiser',
            'Klær og tilbehør',
            'Gaver og veldedighet',
        ],
    },
    'pt-PT': {
        group: 'Padrão',
        income: ['Trabalho'],
        accounts: ['Dinheiro'],
        categories: [
            'Alimentação',
            'Habitação',
            'Transporte',
            'Saúde e Medicina',
            'Educação',
            'Entretenimento',
            'Lazer e Viagens',
            'Roupa e Acessórios',
            'Presentes e Caridade',
        ],
    },
    'sv-SE': {
        group: 'Standard',
        income: ['Arbete'],
        accounts: ['Kontanter'],
        categories: [
            'Mat',
            'Boende',
            'Transport',
            'Hälsa och medicin',
            'Utbildning',
            'Underhållning',
            'Fritid och resor',
            'Kläder och tillbehör',
            'Gåvor och välgörenhet',
        ],
    },

    'uk-UA': {
        group: 'За замовчуванням',
        income: ['Робота'],
        accounts: ['Готівка'],
        categories: [
            'Харчування',
            'Житло',
            'Транспорт',
            "Здоров'я і медицина",
            'Освіта',
            'Розваги',
            'Відпочинок і подорожі',
            'Одяг і аксесуари',
            'Подарунки та благодійність',
        ],
    },
    'ru-RU': {
        group: 'Стандарт',
        income: ['Работа'],
        accounts: ['Наличные'],
        categories: [
            'Еда',
            'Жилье',
            'Транспорт',
            'Здоровье и медицина',
            'Образование',
            'Развлечения',
            'Отдых и путешествия',
            'Одежда и аксессуары',
            'Подарки и благотворительность',
        ],
    },
    'bg-BG': {
        group: 'Стандарт',
        income: ['Работа'],
        accounts: ['Кеш'],
        categories: [
            'Храна',
            'Жилище',
            'Транспорт',
            'Здраве и медицина',
            'Образование',
            'Развлечения',
            'Свободно време и пътувания',
            'Дрехи и аксесоари',
            'Подаръци и благотворителност',
        ],
    },
    'cs-CZ': {
        group: 'Standardní',
        income: ['Práce'],
        accounts: ['Hotovost'],
        categories: [
            'Jídlo',
            'Bydlení',
            'Doprava',
            'Zdraví a medicína',
            'Vzdělání',
            'Zábava',
            'Volný čas a cestování',
            'Oblečení a doplňky',
            'Dárky a charita',
        ],
    },
    'hr-HR': {
        group: 'Standard',
        income: ['Posao'],
        accounts: ['Gotovina'],
        categories: [
            'Hrana',
            'Stanovanje',
            'Prijevoz',
            'Zdravlje i medicina',
            'Obrazovanje',
            'Zabava',
            'Odmor i putovanja',
            'Odjeća i dodaci',
            'Pokloni i dobrotvornost',
        ],
    },
    'hu-HU': {
        group: 'Alapértelmezett',
        income: ['Munka'],
        accounts: ['Készpénz'],
        categories: [
            'Élelmiszer',
            'Lakhatás',
            'Közlekedés',
            'Egészség és gyógyszertár',
            'Oktatás',
            'Szórakozás',
            'Szabadidő és utazás',
            'Ruházat és kiegészítők',
            'Ajándékok és jótékonyság',
        ],
    },
    'ja-JP': {
        group: 'デフォルト',
        income: ['仕事'],
        accounts: ['現金'],
        categories: [
            '食品',
            '住宅',
            '交通',
            '健康と医療',
            '教育',
            'エンターテイメント',
            'レジャーと旅行',
            '衣服とアクセサリー',
            '贈り物とチャリティ',
        ],
    },
    'ka-GE': {
        group: 'სტანდარტული',
        income: ['სამუშაო'],
        accounts: ['ნაღდი ფული'],
        categories: [
            'საკვები',
            'სახლი',
            'ტრანსპორტი',
            'ჯანმრთელობა და მედიცინა',
            'განათლება',
            'გართობა',
            'დასვენება და მოგზაურობა',
            'ტანსაცმელი და აქსესუარები',
            'საჩუქრები და სარგებელი',
        ],
    },
    'pl-PL': {
        group: 'Domyślny',
        income: ['Praca'],
        accounts: ['Gotówka'],
        categories: [
            'Żywność',
            'Mieszkanie',
            'Transport',
            'Zdrowie i medycyna',
            'Edukacja',
            'Rozrywka',
            'Wypoczynek i podróże',
            'Odzież i akcesoria',
            'Prezenty i dobroczynność',
        ],
    },
    'pt-BR': {
        group: 'Padrão',
        income: ['Trabalho'],
        accounts: ['Dinheiro'],
        categories: [
            'Alimentação',
            'Moradia',
            'Transporte',
            'Saúde e Medicina',
            'Educação',
            'Entretenimento',
            'Lazer e Viagens',
            'Roupas e Acessórios',
            'Presentes e Caridade',
        ],
    },
    'ro-RO': {
        group: 'Standard',
        income: ['Muncă'],
        accounts: ['Numerar'],
        categories: [
            'Alimentație',
            'Locuință',
            'Transport',
            'Sănătate și medicină',
            'Educație',
            'Divertisment',
            'Timp liber și călătorii',
            'Îmbrăcăminte și accesorii',
            'Cadouri și caritate',
        ],
    },
    'sk-SK': {
        group: 'Štandard',
        income: ['Práca'],
        accounts: ['Hotovosť'],
        categories: [
            'Potraviny',
            'Bývanie',
            'Doprava',
            'Zdravie a medicína',
            'Vzdelávanie',
            'Zábava',
            'Voľný čas a cestovanie',
            'Oblečenie a doplnky',
            'Darčeky a charita',
        ],
    },
    'sl-SI': {
        group: 'Standard',
        income: ['Delo'],
        accounts: ['Gotovina'],
        categories: [
            'Hrana',
            'Bivanje',
            'Prevoz',
            'Zdravje in medicina',
            'Izobraževanje',
            'Zabava',
            'Prosti čas in potovanja',
            'Oblačila in dodatki',
            'Darila in dobrodelnost',
        ],
    },
    'tr-TR': {
        group: 'Varsayılan',
        income: ['İş'],
        accounts: ['Nakit'],
        categories: [
            'Gıda',
            'Konut',
            'Ulaşım',
            'Sağlık ve Tıp',
            'Eğitim',
            'Eğlence',
            'Boş Zaman ve Seyahat',
            'Giyim ve Aksesuarlar',
            'Hediyeler ve Hayırseverlik',
        ],
    },
    'lv-LV': {
        group: 'Standarta',
        income: ['Darbs'],
        accounts: ['Skaidra nauda'],
        categories: [
            'Pārtika',
            'Mājoklis',
            'Transports',
            'Veselība un medicīna',
            'Izglītība',
            'Izklaide',
            'Atpūta un ceļošana',
            'Apģērbi un aksesuāri',
            'Dāvanas un labdarība',
        ],
    },
};
